# Generated by Django 2.1.5 on 2019-04-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cnpj'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='contrato',
            field=models.CharField(blank=True, max_length=30, verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=4, verbose_name='Percentual desconto %'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='email_cobranca',
            field=models.EmailField(max_length=254, verbose_name='E-mail cobrança'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='forma_pagamento',
            field=models.CharField(choices=[('A VISTA', 'A VISTA'), ('PARCELADO', 'PARCELADO'), ('GRATUIDADE', 'GRATUIDADE')], max_length=20, verbose_name='Forma pagamento'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, verbose_name='Inscrição estadual'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=20, verbose_name='Inscrição municipal'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='meio_pagamento',
            field=models.CharField(choices=[('BOLETO BANCARIO', 'BOLETO BANCARIO'), ('DINHEIRO EM ESPECIE', 'DINHEIRO EM ESPECIE'), ('DEPOSITO EM CONTA', 'DEPOSITO EM CONTA'), ('CARTAO DE CREDITO', 'CARTAO DE CREDITO'), ('CARTAO DE DEBITO', 'CARTAO DE DEBITO'), ('DEBITO EM CONTA', 'DEBITO EM CONTA'), ('GRATUIDADE', 'GRATUIDADE'), ('OUTROS', 'OUTROS')], max_length=20, verbose_name='Meio de pagamento'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nome_fantasia',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='razao_social',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Razão social'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('SUSPENSO', 'SUSPENSO'), ('EXCLUIDO', 'EXCLUIDO'), ('NEGATIVADO', 'NEGATIVADO')], max_length=20, verbose_name='Státus'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='desconto_maximo',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=15, verbose_name='Desconto máximo %'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='descricao',
            field=models.TextField(blank=True, max_length=100, verbose_name='Descricao do plano'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome do plano'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='observacoes',
            field=models.TextField(blank=True, max_length=250, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='valor',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=15, verbose_name='Valor'),
        ),
    ]
