# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas_a_receber', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentosRecebidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status_pagamento', models.CharField(choices=[(b'PENDENTE', b'PENDENTE'), (b'PAGO', b'PAGO'), (b'PARCIALMENTE PAGO', b'PARCIALMENTE PAGO'), (b'CANCELADO', b'CANCELADO')], default=b'PENDENTE', max_length=20)),
                ('meio_pagamento', models.CharField(choices=[(b'DINHEIRO', b'DINHEIRO'), (b'CARTAO DEBITO', b'CARTAO DEBITO'), (b'CARTAO CREDITO', b'CARTAO CREDITO'), (b'CHEQUE', b'CHEQUE'), (b'OUTROS', b'OUTROS')], default=b'OUTROS', max_length=15)),
                ('observacoes_pagamento', models.CharField(blank=True, max_length=200)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas_a_receber.ContasReceber')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresas')),
            ],
            options={
                'ordering': ('data_vencimento', 'valor_pagamento'),
                'db_table': 'pagamentos_recebidos',
            },
        ),
    ]
