# Generated by Django 2.1.5 on 2019-04-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos_recebidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentosrecebidos',
            name='meio_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'DINHEIRO'), ('CARTAO DEBITO', 'CARTAO DEBITO'), ('CARTAO CREDITO', 'CARTAO CREDITO'), ('CHEQUE', 'CHEQUE'), ('OUTROS', 'OUTROS')], default='OUTROS', max_length=15),
        ),
        migrations.AlterField(
            model_name='pagamentosrecebidos',
            name='status_pagamento',
            field=models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('PAGO', 'PAGO'), ('PARCIALMENTE PAGO', 'PARCIALMENTE PAGO'), ('CANCELADO', 'CANCELADO')], default='PENDENTE', max_length=20),
        ),
    ]
