# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('contas_a_receber', '0001_initial'),
        ('empresas', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaProdutos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=15, verbose_name=b'Quantidade')),
                ('data_saida', models.DateField(auto_now_add=True)),
                ('valor_unitario', models.DecimalField(decimal_places=3, default=b'0', max_digits=15, verbose_name=b'Valor unit\xc3\xa1rio')),
                ('percentual_desconto', models.DecimalField(decimal_places=3, default=b'0', max_digits=15, verbose_name=b'Desconto %')),
                ('total_desconto', models.DecimalField(decimal_places=2, default=b'0', max_digits=15, verbose_name=b'Desconto total')),
                ('valor_total', models.DecimalField(decimal_places=2, default=b'0', max_digits=15, verbose_name=b'Valor total')),
                ('status', models.CharField(choices=[(b'EM SEPARACAO', b'EM SEPARACAO'), (b'SEPARADO', b'SEPARADO'), (b'ENTREGUE', b'ENTREGUE'), (b'CANCELADO', b'CANCELADO')], default=b'AGUARDANDO', max_length=20, verbose_name=b'St\xc3\xa1tus')),
                ('balanco', models.CharField(choices=[(b'ABERTO', b'ABERTO'), (b'FECHADO', b'FECHADO')], default=b'ABERTO', max_length=20, verbose_name=b'Balan\xc3\xa7o')),
                ('observacoes_saida', models.TextField(blank=True, max_length=200, verbose_name=b'Observa\xc3\xa7\xc3\xb5es')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=b'0', max_digits=15)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresas')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produtos')),
            ],
            options={
                'ordering': ('-data_saida',),
                'db_table': 'saida_produtos',
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('solicitante', models.CharField(max_length=50, verbose_name=b'Solicitante')),
                ('data_venda', models.DateField(auto_now_add=True)),
                ('data_entrega', models.DateField()),
                ('vencimento', models.DateField(auto_now_add=True)),
                ('status_pedido', models.CharField(default=b'EM ANDAMENTO', max_length=30, verbose_name=b'St\xc3\xa1tus do Pedido')),
                ('valor_total', models.DecimalField(decimal_places=2, default=b'0', max_digits=15, verbose_name=b'Valor total')),
                ('desconto', models.DecimalField(decimal_places=2, default=b'0', max_digits=15, verbose_name=b'Desconto')),
                ('saldo_final', models.DecimalField(decimal_places=2, default=b'0', max_digits=15, verbose_name=b'Saldo final')),
                ('observacoes', models.TextField(blank=True, max_length=200, verbose_name=b'Observa\xc3\xa7\xc3\xb5es')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name=b'CEP')),
                ('endereco', models.CharField(blank=True, max_length=50, verbose_name=b'Endere\xc3\xa7o')),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=30)),
                ('bairro', models.CharField(blank=True, max_length=50, verbose_name=b'Bairro')),
                ('cidade', models.CharField(blank=True, max_length=50, verbose_name=b'Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name=b'Estado')),
                ('observacoes_entrega', models.TextField(blank=True, max_length=200, verbose_name=b'Observa\xc3\xa7\xc3\xb5es')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Clientes')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresas')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contas_a_receber.ContasReceber')),
            ],
            options={
                'ordering': ('-data_venda',),
                'db_table': 'vendas',
            },
        ),
        migrations.AddField(
            model_name='saidaprodutos',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.Vendas', verbose_name=b'Nome/Raz\xc3\xa3o social:'),
        ),
    ]
