# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name=b'Nome')),
                ('sobre_nome', models.CharField(max_length=50, verbose_name=b'Sobre nome')),
                ('rg', models.CharField(blank=True, max_length=15, verbose_name=b'Rg')),
                ('cpf', models.CharField(blank=True, max_length=15, verbose_name=b'Cpf')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name=b'Telefone')),
                ('celular', models.CharField(blank=True, max_length=30, verbose_name=b'Celular')),
                ('email', models.EmailField(blank=True, max_length=30, verbose_name=b'E-mail')),
                ('data_nascimento', models.DateField(verbose_name=b'Data nascimento')),
                ('estado_civil', models.CharField(choices=[(b'SOLTEIRO', b'SOLTEIRO'), (b'CASADO', b'CASADO'), (b'UNIAO ESTAVEL', b'UNIAO ESTAVEL'), (b'DIVORCIADO', b'DIVORCIADO'), (b'SEPARADO', b'SEPARADO'), (b'OUTROS', b'OUTROS')], max_length=15, verbose_name=b'Estado civil')),
                ('sexo', models.CharField(choices=[(b'MASCULINO', b'MASCULINO'), (b'FEMININO', b'FEMININO'), (b'OUTROS', b'OUTROS')], max_length=10, verbose_name=b'Sexo')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name=b'CEP')),
                ('endereco', models.CharField(blank=True, max_length=50, verbose_name=b'Endere\xc3\xa7o')),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=30)),
                ('bairro', models.CharField(blank=True, max_length=50, verbose_name=b'Bairro')),
                ('cidade', models.CharField(blank=True, max_length=50, verbose_name=b'Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name=b'Estado')),
                ('status', models.CharField(choices=[(b'ATIVO', b'ATIVO'), (b'INATIVO', b'INATIVO'), (b'EXCLUIDO', b'EXCLUIDO'), (b'AFASTADO', b'AFASTADO'), (b'APOSENTADO', b'APOSENTADO'), (b'DEMITIDO', b'DEMITIDO')], default=b'ATIVO', max_length=10, verbose_name=b'St\xc3\xa1tus')),
                ('observacoes', models.TextField(blank=True, max_length=200, verbose_name=b'Observa\xc3\xa7\xc3\xb5es')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresas')),
            ],
            options={
                'ordering': ('nome',),
                'db_table': 'colaboradores',
            },
        ),
    ]
