# Generated by Django 2.1.5 on 2019-04-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='celular',
            field=models.CharField(blank=True, max_length=30, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, verbose_name='Cpf'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data nascimento'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='email',
            field=models.EmailField(blank=True, max_length=30, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='endereco',
            field=models.CharField(blank=True, max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='estado',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTEIRO', 'SOLTEIRO'), ('CASADO', 'CASADO'), ('UNIAO ESTAVEL', 'UNIAO ESTAVEL'), ('DIVORCIADO', 'DIVORCIADO'), ('SEPARADO', 'SEPARADO'), ('OUTROS', 'OUTROS')], max_length=15, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='observacoes',
            field=models.TextField(blank=True, max_length=200, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='rg',
            field=models.CharField(blank=True, max_length=15, verbose_name='Rg'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO'), ('OUTROS', 'OUTROS')], max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='sobre_nome',
            field=models.CharField(max_length=50, verbose_name='Sobre nome'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('EXCLUIDO', 'EXCLUIDO'), ('AFASTADO', 'AFASTADO'), ('APOSENTADO', 'APOSENTADO'), ('DEMITIDO', 'DEMITIDO')], default='ATIVO', max_length=10, verbose_name='Státus'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone'),
        ),
    ]
