# Generated by Django 2.1.5 on 2019-04-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20181108_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='celular',
            field=models.CharField(blank=True, max_length=30, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cidade',
            field=models.CharField(max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contato',
            field=models.CharField(blank=True, max_length=30, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpf_cnpj',
            field=models.CharField(max_length=20, verbose_name='Cpf'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='data_nascimento_fundacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data nascimento'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='endereco',
            field=models.CharField(blank=True, max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estado',
            field=models.CharField(max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=15, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=15, verbose_name='Rg ou inscição estadual'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome fantasia'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome_razao_social',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='observacoes',
            field=models.TextField(blank=True, max_length=200, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='pessoa',
            field=models.CharField(max_length=10, verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='rg_inscricao_estadual',
            field=models.CharField(blank=True, max_length=15, verbose_name='Rg ou inscição estadual'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='sobre_nome',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sobre nome'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='status',
            field=models.CharField(default='ATIVO', max_length=20, verbose_name='Státus'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone'),
        ),
    ]
