# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-22 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=100, verbose_name=b'Nome fantasia'),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='nome_razao_social',
            field=models.CharField(max_length=100, verbose_name=b'Nome'),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='sobre_nome',
            field=models.CharField(blank=True, max_length=100, verbose_name=b'Sobre nome'),
        ),
    ]
