from django import forms
from cadastros.usuarios.models import Usuarios, Permissoes


class FormCadastroUsuarios(forms.ModelForm):
    class Meta:
        model = Usuarios
        fields = (
            'nome',
            'colaborador',
            'cpf',
            'email',
            'status',
            'permissoes',
            'observacoes',
        )


class FormPermissoesUsuarios(forms.ModelForm):
    class Meta:
        model = Permissoes
        fields = (
            'descricao',
            'administrador',
            'administrador_super',
            'cadastra_colaborador',
            'edita_colaborador',
            'acessa_cadastro_colaboradores',
            'muda_status_colaborador',
            'cadastra_usuario',
            'edita_usuario',
            'acessa_cadastro_usuarios',
            'muda_status_usuario',
            'cadastra_cliente',
            'edita_cliente',
            'acessa_cadastro_cliente',
            'muda_status_cliente',
            'cadastra_fornecedor',
            'edita_fornecedor',
            'acessa_cadastro_fornecedor',
            'muda_status_fornecedor',
            'cadastra_produto',
            'edita_produto',
            'acessa_cadastro_produto',
            'muda_status_produto',
            'altera_preco_produto',
            'anuncia_produto',
            'registra_venda',
            'edita_venda',
            'fecha_venda',
            'acessa_registro_venda',
            'muda_status_venda',
            'cancela_venda',
            'imprime_cupom_venda',
            'cadastra_permissoes_usuario',
            'edita_permissoes_usuario',
            'acessa_permissoes_usuario',
            'muda_status_permissoes_usuario',
            'exclui_permissoes_usuario',
            'tabela_preco',
            'edita_tabela_de_precos',
            'acessa_tabela_de_precos',
            'exclui_preco_tabelado',
            'registra_compra',
            'edita_compra',
            'acessa_registro_compra',
            'muda_status_compra',
            'cancela_compra',
            'finaliza_compra',
            'edita_contas_pagar',
            'acessa_contas_pagar',
            'exclui_contas_pagar',
            'quita_contas_pagar',
            'edita_contas_receber',
            'acessa_contas_receber',
            'exclui_contas_receber',
            'quita_contas_receber',
            'registra_pagamento',
            'edita_pagamento',
            'acessa_pagamento',
            'muda_status_pagamento',
            'exclui_pagamento',
            'registra_recebimento',
            'edita_recebimento',
            'acessa_recebimento',
            'muda_status_recebimento',
            'exclui_recebimento',
            'registra_entrada_produto',
            'edita_entrada_produto',
            'acessa_entrada_produto',
            'muda_status_entrada_produto',
            'cancela_entrada_produto',
            'registra_saida_produto',
            'edita_saida_produto',
            'muda_status_saida_produto',
            'acessa_saida_produto',
            'cancela_saida_produto',
            'publica_conteudo_site',
            'exclui_conteudo_site',
            'edita_conteudo_site',
            'muda_status_conteudo_site',
            'acessa_conteudo_site',
            'publica_mensagem_site',
            'exclui_mensagem_site',
            'edita_mensagem_site',
            'muda_status_mensagem_site',
            'acessa_mensagem_site',
            'observacoes',
        )

