# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagensProdutos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=b'produtos/img')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresas')),
            ],
            options={
                'ordering': ['imagem'],
                'db_table': 'imagens_produtos',
            },
        ),
        migrations.CreateModel(
            name='PrecosPomocionais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_desconto', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('preco_venda_promocao', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('inicio_promocao', models.DateField()),
                ('fim_promocao', models.DateField()),
                ('status_promocao', models.CharField(default=b'ATIVO', max_length=10)),
                ('observacoes_promocao', models.TextField(blank=True, max_length=200)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresas')),
            ],
            options={
                'ordering': ('produto_promocao',),
                'db_table': 'precos_promocionais',
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_simplificada', models.CharField(max_length=32, null=True)),
                ('unidade_medida', models.CharField(max_length=10)),
                ('categoria', models.CharField(max_length=30)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=b'0.0', max_digits=15)),
                ('estoque_maximo', models.DecimalField(decimal_places=3, default=b'0.0', max_digits=15)),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=b'0.0', max_digits=15)),
                ('fracionar_produto', models.CharField(max_length=5)),
                ('id_embalagem_fechada', models.IntegerField(default=b'0')),
                ('quantidade_embalagem_fechada', models.DecimalField(decimal_places=3, default=b'0', max_digits=15)),
                ('valor_compra', models.DecimalField(decimal_places=3, default=b'0', max_digits=15)),
                ('percentual_lucro', models.DecimalField(decimal_places=3, default=b'0', max_digits=15)),
                ('desconto_maximo', models.DecimalField(decimal_places=3, default=b'0', max_digits=5)),
                ('atacado_apartir', models.DecimalField(decimal_places=3, default=b'0', max_digits=15)),
                ('atacado_desconto', models.DecimalField(decimal_places=3, default=b'0', max_digits=5)),
                ('status', models.CharField(default=b'ATIVO', max_length=20)),
                ('observacoes', models.TextField(blank=True, max_length=200)),
                ('marketing', models.CharField(blank=True, max_length=200, null=True)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=b'0', max_digits=15)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('marca', models.CharField(max_length=30)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('anunciar_produto', models.IntegerField(default=0)),
                ('descricao_completa', models.CharField(blank=True, max_length=200, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresas')),
                ('imagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.ImagensProdutos')),
            ],
            options={
                'ordering': ('descricao_simplificada',),
                'db_table': 'produtos',
            },
        ),
        migrations.CreateModel(
            name='TabelaPrecos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('preco_venda', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('observacoes_preco', models.TextField(blank=True, max_length=200)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('status_preco', models.CharField(default=b'ATIVO', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Clientes')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresas')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produtos')),
            ],
            options={
                'ordering': ('produto',),
                'db_table': 'tabela_precos',
            },
        ),
        migrations.AddField(
            model_name='precospomocionais',
            name='produto_promocao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produtos'),
        ),
    ]
