# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20181021_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(blank=True, default=b'produtos/img/generic.png', null=True, upload_to=b'produtos/img'),
        ),
    ]
