# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-22 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20181021_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(blank=True, default=b'estoque/produtos/img/generic.png', null=True, upload_to=b'estoque/produtos/img/'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='marketing',
            field=models.CharField(blank=True, default=b'', max_length=200, null=True),
        ),
    ]
