# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20181022_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='codigo_barras',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtos',
            name='marketing',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
