# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-25 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20181025_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagensprodutos',
            name='produto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='produtos.Produtos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagensprodutos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=b'estoque/produtos/img/'),
        ),
    ]
