# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-25 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_auto_20181025_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='descricao_completa',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='descricao_simplificada',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
