# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-25 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_auto_20181025_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagensprodutos',
            name='imagem',
            field=models.ImageField(null=True, upload_to=b'estoque/produtos/img/'),
        ),
    ]
