# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_auto_20181025_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagensprodutos',
            name='sequencia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='imagensprodutos',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
