# Generated by Django 2.1.5 on 2019-04-26 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20190426_1228'),
        ('produtos', '0011_auto_20181108_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresas')),
            ],
            options={
                'db_table': 'categorias_produtos',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresas')),
            ],
            options={
                'db_table': 'marcas_produtos',
                'ordering': ('descricao',),
            },
        ),
        migrations.AlterField(
            model_name='imagensprodutos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='estoque/produtos/img/'),
        ),
        migrations.AlterField(
            model_name='precospomocionais',
            name='status_promocao',
            field=models.CharField(default='ATIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='atacado_apartir',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=15),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='atacado_desconto',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='desconto_maximo',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='estoque_atual',
            field=models.DecimalField(decimal_places=3, default='0.0', max_digits=15),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='estoque_maximo',
            field=models.DecimalField(decimal_places=3, default='0.0', max_digits=15),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=3, default='0.0', max_digits=15),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='id_embalagem_fechada',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(blank=True, default='', null=True, upload_to='estoque/produtos/img/'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='marketing',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='percentual_lucro',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=15),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=15),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='quantidade_embalagem_fechada',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=15),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='status',
            field=models.CharField(default='ATIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='valor_compra',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=15),
        ),
        migrations.AlterField(
            model_name='tabelaprecos',
            name='status_preco',
            field=models.CharField(default='ATIVO', max_length=10),
        ),
    ]
