# Generated by Django 2.1.5 on 2019-04-27 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_auto_20190426_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Categorias'),
        ),
    ]
