# Generated by Django 2.1.5 on 2019-04-27 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_auto_20190427_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Marcas'),
        ),
    ]
