# Generated by Django 2.1.5 on 2019-04-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_auto_20190427_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='categoria',
            new_name='categoria_produto',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='marca',
            new_name='marca_produto',
        ),
    ]
