# Generated by Django 2.1.5 on 2019-04-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_auto_20190427_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='descricao_simplificada',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
