# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasReceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conta', models.DateField(auto_now_add=True)),
                ('valor_conta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('forma_de_pagamento', models.CharField(choices=[(b'A VISTA', b'A VISTA'), (b'A PRAZO', b'A PRAZO')], max_length=8)),
                ('meio_de_pagamento', models.CharField(choices=[(b'DINHEIRO', b'DINHEIRO'), (b'CARTAO DEBITO', b'CARTAO DEBITO'), (b'CARTAO CREDITO', b'CARTAO CREDITO'), (b'CHEQUE', b'CHEQUE'), (b'OUTROS', b'OUTROS')], max_length=15)),
                ('quantidade_parcelas', models.IntegerField(default=b'1')),
                ('primeiro_vencimento', models.DateField()),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('documento_vinculado', models.IntegerField(blank=True, default=0, null=True, unique=True)),
                ('status_conta', models.CharField(choices=[(b'PENDENTE', b'PENDENTE'), (b'PARCIALMENTE PAGO', b'PARCIALMENTE PAGO'), (b'PAGO', b'PAGO'), (b'CANCELADO', b'CANCELADO')], default=b'PENDENTE', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('observacoes_conta', models.CharField(blank=True, max_length=200)),
                ('agente_pagador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Clientes')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresas')),
            ],
            options={
                'ordering': ('-data_conta', 'valor_conta'),
                'db_table': 'contas_a_receber',
            },
        ),
    ]
