# Generated by Django 2.1.5 on 2019-04-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_receber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contasreceber',
            name='forma_de_pagamento',
            field=models.CharField(choices=[('A VISTA', 'A VISTA'), ('A PRAZO', 'A PRAZO')], max_length=8),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='meio_de_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'DINHEIRO'), ('CARTAO DEBITO', 'CARTAO DEBITO'), ('CARTAO CREDITO', 'CARTAO CREDITO'), ('CHEQUE', 'CHEQUE'), ('OUTROS', 'OUTROS')], max_length=15),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='quantidade_parcelas',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='status_conta',
            field=models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('PARCIALMENTE PAGO', 'PARCIALMENTE PAGO'), ('PAGO', 'PAGO'), ('CANCELADO', 'CANCELADO')], default='PENDENTE', max_length=20),
        ),
    ]
